service: connect-demo

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

  region: ap-northeast-1

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

custom:
  SUFFIX: "mk" # 一意の名前を入力してください

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    ConnectInstance:
      Type: AWS::Connect::Instance
      Properties: 
        Attributes: 
          InboundCalls: true
          OutboundCalls: true
        IdentityManagementType: CONNECT_MANAGED
        InstanceAlias: scsk-rdc-${self:custom.SUFFIX}

  Outputs:
    NewOutput:
      Description: "Description for the output"
      Value: "Some output value"
